### ISSUE TITLE
Doesn't work anymore on latest Android Studio Arctic Fox stable

### ISSUE THREAD

**Issue by andob** [JetBrains/rider-theme-pack#11]
Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 26, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: Rider UI Theme Pack, com.dmarcotte.handlebars, manifold.ij, com.intellij.marketplace, Dart, com.thoughtworks.gauge, org.jetbrains.kotlin, io.flutter, com.itkacher.okhttpprofiler, org.intellij.plugins.markdown

**Comment by andob** [comment]
Plugin is installed:

![image](https://user-images.githubusercontent.com/5281358/127468438-f47407f2-b734-4560-ae61-40bbb8ec86d5.png)

Yet it won't show up:

![image](https://user-images.githubusercontent.com/5281358/127468512-62921e5c-ec1b-4f02-a06f-58283ba2230e.png)

![image](https://user-images.githubusercontent.com/5281358/127468558-44b3e670-79d6-4260-b5af-cafde4ba6582.png)

**Comment by nikunjparadva** [comment]
## Here is the Solution
https://stackoverflow.com/a/68599712/5773037

**Comment by andob** [comment]
this is a workaround. so it's an IDE issue. will close this issue.
